-- =====================================================================================
--  TRANSFERT DE PARC UNIFIÉ — MODÈLE DE PERSISTANCE DE LA DEMANDE
--  Cible : Oracle 11g R2. Acquisition synchrone Java, workers asynchrones Python,
--          packages PL/SQL.
--
--    INF915_REF_OPERATION   le référentiel des opérations déduites
--    INF915_NOTIFICATIONS   l'en-tête : qui, quoi, quand
--    INF915_ACTION          l'historique de la demande : création, validation,
--                           annulation, relance, début et fin de traitement
--    INF915_OBJET_PARENT    les objets parents du périmètre et leur cible
--    INF915_LIGNE           le périmètre lui-même, une ligne par IDS
--    INF915_CONTROLE        pourquoi une ligne a été exclue
--    INF915_EVENEMENT       le journal d'exécution, ligne par ligne
--
--  DEUX HISTORIQUES, DEUX GRANULARITÉS
--    INF915_ACTION porte l'histoire de la DEMANDE : quelques lignes par demande,
--    un acteur identifié, une portée métier. C'est ce que l'écran de suivi affiche
--    dans le panneau « historique », et ce que l'audit conserve des années.
--    INF915_EVENEMENT porte le journal des LIGNES et des objets parents : plusieurs
--    dizaines de milliers de lignes pour une grosse demande, purgeable après quelques
--    mois sans rien perdre de la traçabilité métier.
--    Les deux sont reliés : un événement produit par une relance porte l'ID_ACTION
--    de cette relance, ce qui permet de retrouver quelles lignes une relance donnée
--    a effectivement touchées.
--
--  ADAPTATIONS 11g PAR RAPPORT À UNE ÉCRITURE 12c
--    - pas de colonne IDENTITY : une séquence et un trigger BEFORE INSERT par table,
--      avec le test IS NULL qui reproduit la sémantique GENERATED BY DEFAULT ;
--    - le référentiel est créé en premier, la clé étrangère de l'en-tête le référence ;
--    - aucune contrainte IS JSON, aucun DEFAULT ON NULL, aucune colonne virtuelle ;
--    - tous les identifiants tiennent dans 30 caractères.
--
--  LE TRAITEMENT EST PILOTÉ PAR LA DONNÉE, PAS PAR L'ACTE
--  Aucun traitement ne lit CODE_OPERATION pour décider quoi faire. Le worker lit
--  INF915_OBJET_PARENT pour savoir quels objets créer ou réutiliser, puis
--  INF915_LIGNE pour savoir quelles BdS déplacer et vers quel rattachement. Ces deux
--  tables suffisent, quel que soit l'acte. CODE_OPERATION n'existe que pour le
--  reporting, l'écran de suivi et la comparaison avec les huit actes historiques.
--  Il est calculé après coup par le worker Python via INF915_PY, il est
--  facultatif, et une qualification erronée n'a aucune conséquence sur le transfert.
--  C'est la raison pour laquelle INF915_REF_OPERATION ne porte pas de nom de package
--  de traitement : il n'y a pas un package par acte, il y a un seul traitement.
--
--  RÈGLE DE NORMALISATION
--  Seuls les identifiants techniques sont stockés. Les libellés, numéros de contrat,
--  SITE_ID et noms de lot restent dans le référentiel Clarify et sont résolus à
--  l'affichage. La restitution d'une demande ancienne affiche donc les libellés
--  d'aujourd'hui, et la requête d'affichage doit joindre TABLE_CONTRACT, TABLE_SITE
--  ou TABLE_CONTR_SCHEDULE selon INF915_OBJET_PARENT.TYPE_OBJET.
--
--  SEULE EXCEPTION : les compteurs de INF915_NOTIFICATIONS, pour que l'écran de suivi
--  affiche une liste de demandes sans agréger à chaud. Ils sont toujours mis à jour en
--  incrémental (SET NB = NB + 1). La vue INF915_V_VOLUMETRIE donne l'équivalent
--  recalculé si vous préférez les supprimer.
--
--  PRINCIPES ISSUS DE L'ANALYSE DE L'EXISTANT
--    1. Aucune colonne dont le sens dépend du type d'acte (leçon de X_AV_FOCUS_ID).
--    2. Les objid sont résolus une seule fois, à la validation, et figés (leçon de
--       ChmtCF, qui résout les sites par SITE_ID à chaque passage du batch).
--    3. Pas de demande fille : les lignes rattachées à un accès entrent dans
--       INF915_LIGNE avec un lien vers leur porteuse (leçon de ChmtCFAccesFull).
--    4. Deux phases d'exécution, deux tables : INF915_OBJET_PARENT pilote la phase
--       séquentielle, INF915_LIGNE la phase parallèle.
--    5. Ne sont pas stockés : les remises, recalculées par le rattachement de la
--       version commerciale à la grille du contrat cible, et les options de niveau
--       ligne, transférées telles quelles.
-- =====================================================================================


-- =====================================================================================
--  0. DÉSINSTALLATION  (à décommenter pour rejouer le script)
-- =====================================================================================
-- DROP VIEW  INF915_V_VOLUMETRIE;
-- DROP VIEW  INF915_V_SUIVI;
-- DROP VIEW  INF915_V_JALON;
-- DROP TABLE INF915_EVENEMENT      CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_CONTROLE       CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_LIGNE          CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_OBJET_PARENT   CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_ACTION         CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_NOTIFICATIONS  CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_REF_OPERATION  CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_TMP_LIGNE      CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INF915_TMP_CIBLE      CASCADE CONSTRAINTS PURGE;
-- DROP SEQUENCE SEQ_INF915_NOTIF;
-- DROP SEQUENCE SEQ_INF915_ACTION;
-- DROP SEQUENCE SEQ_INF915_PARENT;
-- DROP SEQUENCE SEQ_INF915_LIGNE;
-- DROP SEQUENCE SEQ_INF915_CTRL;
-- DROP SEQUENCE SEQ_INF915_EVT;


-- =====================================================================================
--  1. RÉFÉRENTIEL DES OPÉRATIONS DÉDUITES
--     Créé en premier : INF915_NOTIFICATIONS y fait référence.
-- =====================================================================================
CREATE TABLE INF915_REF_OPERATION (
  CODE_OPERATION        VARCHAR2(40)    NOT NULL,
  LIBELLE               VARCHAR2(160)   NOT NULL,
  ACTE_HISTORIQUE       VARCHAR2(60),   -- correspondance avec les actes d'avant
  ACTIF                 NUMBER(1)       DEFAULT 1 NOT NULL,
  CONSTRAINT PK_INF915_REF_OP PRIMARY KEY (CODE_OPERATION)
);

COMMENT ON TABLE INF915_REF_OPERATION IS
  'Libelles des operations deduites, pour le reporting. Aucune colonne de routage : le traitement ne depend pas de l acte mais du contenu de INF915_OBJET_PARENT et INF915_LIGNE.';

INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('CHGT_SITE_FACTURATION','Changement de site de facturation','Changement payeur',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('REORG_FACT_CENTRA','Réorganisation de la structure de facture - centralisation','Structure Fact',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('REORG_FACT_DECENTRA','Réorganisation de la structure de facture - décentralisation','Structure Fact',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('CHGT_SITE_INSTALLATION','Changement de site d''installation','Transfert administratif',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('CHGT_SI_ET_CF','Changement de SI et de CF','Transfert administratif',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('TRANSFERT_INTER_CONTRAT','Transfert inter-contrat','Transfert administratif et Fusac',1);
INSERT INTO INF915_REF_OPERATION (CODE_OPERATION, LIBELLE, ACTE_HISTORIQUE, ACTIF)
VALUES ('CHGT_TITULAIRE','Changement de titulaire','CTI',1);
COMMIT;


-- =====================================================================================
--  2. EN-TÊTE DE LA DEMANDE
--     Plus aucune colonne d'audit : tout est dans INF915_ACTION.
-- =====================================================================================
CREATE TABLE INF915_NOTIFICATIONS (
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_NOTIF_BI
  REFERENCE             VARCHAR2(20)    NOT NULL,   -- TR-2026-004871, visible du métier

  -- Organisation : mono-valuée des deux côtés, donc portée par l'en-tête.
  -- ID_ORGA_CIBLE à NULL signifie que l'organisation est conservée.
  ID_ORGA_SOURCE        NUMBER(12)      NOT NULL,   -- OBJID Clarify
  ID_ORGA_CIBLE         NUMBER(12),

  -- Maille et opération déduite. Le détail de ce qui change, type d'objet par type
  -- d'objet, se lit dans INF915_OBJET_PARENT : une demande peut parfaitement créer
  -- une partie des sites et en réutiliser une autre.
  MAILLE                VARCHAR2(10)    NOT NULL,   -- MASSE | SELECTION

  -- Étiquette informative, qualifiée après coup par le worker. Facultative : une
  -- demande se traite sans, et une qualification erronée n'a aucune conséquence sur
  -- le transfert. Voir la note sur le pilotage par la donnée, plus bas.
  CODE_OPERATION        VARCHAR2(40),

  -- Exécution
  DATE_EFFET            DATE            NOT NULL,
  STATUT                VARCHAR2(22)    NOT NULL,

  -- Volumétrie du périmètre, figée à la validation
  NB_LIGNES             NUMBER(8)       DEFAULT 0 NOT NULL,
  NB_CONTRATS           NUMBER(6)       DEFAULT 0 NOT NULL,
  NB_SI                 NUMBER(6)       DEFAULT 0 NOT NULL,
  NB_CF                 NUMBER(6)       DEFAULT 0 NOT NULL,
  NB_LOTS               NUMBER(6)       DEFAULT 0 NOT NULL,

  -- Avancement, incrémenté par les workers
  NB_LIGNES_OK          NUMBER(8)       DEFAULT 0 NOT NULL,
  NB_LIGNES_KO_METIER   NUMBER(8)       DEFAULT 0 NOT NULL,
  NB_LIGNES_KO_TECH     NUMBER(8)       DEFAULT 0 NOT NULL,
  NB_OBJETS_A_CREER     NUMBER(6)       DEFAULT 0 NOT NULL,
  NB_OBJETS_CREES       NUMBER(6)       DEFAULT 0 NOT NULL,

  CONSTRAINT PK_INF915_NOTIF        PRIMARY KEY (ID_NOTIFICATION),
  CONSTRAINT UK_INF915_NOTIF_REF    UNIQUE (REFERENCE),
  CONSTRAINT FK_INF915_NOTIF_OP     FOREIGN KEY (CODE_OPERATION)
      REFERENCES INF915_REF_OPERATION (CODE_OPERATION),
  CONSTRAINT CK_INF915_NOTIF_MAILLE CHECK (MAILLE IN ('MASSE','SELECTION')),
  CONSTRAINT CK_INF915_NOTIF_ORGA   CHECK (ID_ORGA_CIBLE IS NULL OR ID_ORGA_CIBLE <> ID_ORGA_SOURCE),
  CONSTRAINT CK_INF915_NOTIF_STATUT CHECK (STATUT IN (
      'EN_ATTENTE',         -- statut initial : la demande existe donc elle est valide.
                            -- Attend sa date d'effet, ou la prise en charge d'un worker
      'EN_COURS_PARENTS',   -- phase 1 : création des objets parents
      'PARENTS_CREES',      -- phase 1 terminée. SEUL POINT D'ARRÊT du cycle : le métier
                            -- vérifie les objets créés, corrige si besoin, puis lance
      'PARENTS_EN_ERREUR',  -- phase 1 partiellement en échec, correction attendue
      'EN_ATTENTE_TRT_LIGNES', -- feu vert donné par le métier, en attente de la prise
                            -- en charge d'un worker. Dernier statut annulable.
      'EN_COURS_LIGNES',    -- phase 2 : résiliation et recréation des BdS
      'TRAITEE',
      'TRAITEE_PARTIELLE',
      'EN_ERREUR',
      'ANNULEE'))
);

CREATE INDEX IX_INF915_NOTIF_ORGA ON INF915_NOTIFICATIONS (ID_ORGA_SOURCE);
CREATE INDEX IX_INF915_NOTIF_PLAN ON INF915_NOTIFICATIONS (STATUT, DATE_EFFET);

COMMENT ON TABLE  INF915_NOTIFICATIONS IS 'En-tete d une demande de transfert de parc, tous types d operation confondus';
COMMENT ON COLUMN INF915_NOTIFICATIONS.CODE_OPERATION IS 'Etiquette informative, qualifiee par le worker apres coup. Ne pilote aucun traitement : voir INF915_PY.';
COMMENT ON COLUMN INF915_NOTIFICATIONS.ID_ORGA_CIBLE IS 'NULL si l organisation est conservee. Renseigne, la demande est un changement de titulaire.';

-- La liste de suivi se trie sur ID_NOTIFICATION DESC, qui suit l'ordre de création
-- puisqu'il vient d'une séquence. Aucun index sur une date de création n'est donc
-- nécessaire sur cette table.
--
-- =====================================================================================
--  CYCLE DE VIE D'UNE DEMANDE
--
--  Une demande n'existe en base que si elle est valide. La saisie et les contrôles
--  d'éligibilité ont lieu en amont, dans le service web synchrone d'acquisition :
--    - les brouillons ne sont pas stockés ici, ils vivent dans l'application appelante ;
--    - les contrôles sont joués avant l'écriture, et les lignes en échec sont rendues
--      au conseiller sans jamais entrer dans INF915_LIGNE ;
--    - il n'y a donc ni statut BROUILLON, ni statut CONTROLEE, ni étape de validation
--      distincte de la création. Écrire la demande, c'est la valider.
--
--          EN_ATTENTE ──────────────────────────────┐
--               │                                    │
--               ▼                (aucun objet à créer)
--       EN_COURS_PARENTS                             │
--               │                                    │
--      ┌────────┴─────────┐                          │
--      ▼                  ▼                          │
--   PARENTS_CREES ◄─ PARENTS_EN_ERREUR               │
--       │                  │  (correction, relance)  │
--       │  POINT D'ARRÊT : feu vert du métier        │
--       ▼                                            │
--   EN_ATTENTE_TRT_LIGNES                            │
--       │  (prise en charge d'un worker)             │
--  ═════│════════════════════════════════════════════│═════════════════════════
--       │        FRONTIÈRE D'IRRÉVERSIBILITÉ         │
--       ▼                                            ▼
--   EN_COURS_LIGNES ──┬──► TRAITEE
--          ▲          ├──► TRAITEE_PARTIELLE
--          │          └──► EN_ERREUR
--          └───────── (relance des lignes en échec)
--
--   ANNULEE ◄── EN_ATTENTE, PARENTS_CREES, PARENTS_EN_ERREUR, EN_ATTENTE_TRT_LIGNES
--               c'est-à-dire tous les statuts situés au-dessus de la frontière,
--               et eux seuls.
--
--  LE SEUL POINT D'ARRÊT
--  La phase séquentielle crée des contrats, des sites et des lots qui n'existaient pas.
--  Ces objets sont vérifiables et corrigeables tant qu'aucune BdS n'a bougé, et c'est
--  la seule chose que le métier ne peut pas contrôler avant, puisqu'elle n'existe pas
--  encore au moment de la saisie. La demande s'arrête donc là et attend une action
--  explicite, tracée dans INF915_ACTION sous le type VALIDATION_PARENTS. Aucun worker
--  ne franchit ce jalon tout seul.
--
--  Quand NB_OBJETS_A_CREER vaut zéro, il n'y a rien à vérifier : la demande passe
--  directement de EN_ATTENTE à EN_COURS_LIGNES. Le trigger autorise cette transition
--  pour ce seul cas et la refuse dès qu'un objet est à créer.
--
--  DEUX STATUTS D'ATTENTE, POUR LA MÊME RAISON
--  EN_ATTENTE et EN_ATTENTE_TRT_LIGNES séparent l'un et l'autre une décision de sa
--  prise en charge. Le métier valide, mais c'est le worker qui démarre, et il peut le
--  faire des heures plus tard. Sans ce statut intermédiaire, une demande dont le feu
--  vert vient d'être donné serait affichée « en cours » alors que rien ne tourne.
--
--  LA RÈGLE D'ANNULATION
--  ANNULEE est atteignable tant qu'aucune BdS n'a bougé, c'est-à-dire depuis
--  EN_ATTENTE, PARENTS_CREES, PARENTS_EN_ERREUR et EN_ATTENTE_TRT_LIGNES. Dès
--  EN_COURS_LIGNES, des BdS sont résiliées et recréées, et une annulation ne les
--  rétablirait pas : il ne reste que la relance des lignes en échec, ou la clôture en
--  TRAITEE_PARTIELLE puis TRAITEE. Le trigger fait respecter cette règle.
--
--  Une relance après échec repart directement en EN_COURS_LIGNES et non par
--  EN_ATTENTE_TRT_LIGNES : la demande est déjà engagée, il n'y a plus de feu vert à
--  donner, et faire repasser par un statut annulable rouvrirait une porte qui doit
--  rester fermée.
--
--  Nota : une annulation en PARENTS_CREES ne supprime pas les objets déjà créés dans
--  le parc. Le métier doit en disposer lui-même s'il le souhaite.
-- =====================================================================================


-- =====================================================================================
--  3. HISTORIQUE DE LA DEMANDE
--     Une ligne par action sur la demande, humaine ou automatique.
--     Remplace les colonnes CREE_PAR, DATE_CREATION, VALIDE_PAR, DATE_VALIDATION,
--     DATE_DEBUT_TRT et DATE_FIN_TRT de l'en-tête, qui ne savaient représenter
--     ni l'annulation, ni les relances successives.
-- =====================================================================================
CREATE TABLE INF915_ACTION (
  ID_ACTION             NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_ACTION_BI
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,

  TYPE_ACTION           VARCHAR2(20)    NOT NULL,
  ACTEUR                VARCHAR2(40)    NOT NULL,   -- login, ou identifiant du worker
  TYPE_ACTEUR           VARCHAR2(12)    NOT NULL,   -- UTILISATEUR | SYSTEME
  DATE_ACTION           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

  -- Transition de statut provoquée par l'action, quand il y en a une
  STATUT_AVANT          VARCHAR2(22),
  STATUT_APRES          VARCHAR2(22),

  -- Portée, utile sur les relances partielles : combien de lignes ont été relancées,
  -- et sur quel critère. Le détail ligne par ligne est dans INF915_EVENEMENT,
  -- dont les lignes portent l'ID_ACTION.
  NB_LIGNES_VISEES      NUMBER(8),
  PORTEE                VARCHAR2(40),               -- TOUTES | ERREUR_TECH | ERREUR_METIER | SELECTION

  -- Motif d'annulation, commentaire de relance, cause d'un échec système
  MOTIF                 VARCHAR2(500),

  CONSTRAINT PK_INF915_ACTION       PRIMARY KEY (ID_ACTION),
  CONSTRAINT FK_INF915_ACTION_NOT   FOREIGN KEY (ID_NOTIFICATION)
      REFERENCES INF915_NOTIFICATIONS (ID_NOTIFICATION) ON DELETE CASCADE,
  CONSTRAINT CK_INF915_ACTION_TYPE  CHECK (TYPE_ACTION IN (
      'CREATION',            -- écriture de la demande, contrôles déjà passés en amont
      'DEBUT_PARENTS',       -- prise en charge de la phase séquentielle
      'FIN_PARENTS',         -- objets parents créés, demande en attente du feu vert
      'VALIDATION_PARENTS',  -- feu vert du métier après vérification des objets créés
      'DEBUT_LIGNES',        -- prise en charge de la phase parallèle
      'FIN_TRAITEMENT',      -- fin de traitement, partielle ou complète
      'ANNULATION',          -- demande abandonnée, qui et pourquoi
      'RELANCE')),           -- relance de lignes en erreur, qui et sur quelle portée
  CONSTRAINT CK_INF915_ACTION_ACTEU CHECK (TYPE_ACTEUR IN ('UTILISATEUR','SYSTEME')),
  CONSTRAINT CK_INF915_ACTION_PORT  CHECK (PORTEE IS NULL OR PORTEE IN
      ('TOUTES','ERREUR_TECH','ERREUR_METIER','SELECTION')),
  -- une annulation doit être motivée
  CONSTRAINT CK_INF915_ACTION_MOTIF CHECK (TYPE_ACTION <> 'ANNULATION' OR MOTIF IS NOT NULL),
  -- une relance doit dire ce qu'elle vise
  CONSTRAINT CK_INF915_ACTION_RELAN CHECK (TYPE_ACTION <> 'RELANCE' OR PORTEE IS NOT NULL)
);

CREATE INDEX IX_INF915_ACTION_NOT ON INF915_ACTION (ID_NOTIFICATION, DATE_ACTION);
CREATE INDEX IX_INF915_ACTION_ACT ON INF915_ACTION (ACTEUR, DATE_ACTION);
CREATE INDEX IX_INF915_ACTION_TYP ON INF915_ACTION (TYPE_ACTION, DATE_ACTION);

-- Une demande n'a qu'une création et qu'une annulation. Index unique fonctionnel :
-- les lignes dont l'expression est NULL ne sont pas indexées, la contrainte ne porte
-- donc que sur les actions du type visé.
CREATE UNIQUE INDEX UX_INF915_ACTION_CREA ON INF915_ACTION
  (CASE WHEN TYPE_ACTION = 'CREATION'   THEN ID_NOTIFICATION END);
CREATE UNIQUE INDEX UX_INF915_ACTION_ANNU ON INF915_ACTION
  (CASE WHEN TYPE_ACTION = 'ANNULATION' THEN ID_NOTIFICATION END);

COMMENT ON TABLE INF915_ACTION IS
  'Historique de la demande : qui a cree, qui a valide les objets parents, qui a annule et pourquoi, qui a relance et sur quelle portee. La creation vaut validation : les controles sont passes en amont par le service d acquisition.';
COMMENT ON COLUMN INF915_ACTION.TYPE_ACTEUR IS
  'UTILISATEUR pour une action humaine, SYSTEME pour une action de worker ou d ordonnanceur. Permet de filtrer l historique metier du bruit technique.';
COMMENT ON COLUMN INF915_ACTION.PORTEE IS
  'Sur une relance : quelles lignes ont ete visees. Le detail ligne par ligne se retrouve dans INF915_EVENEMENT via ID_ACTION.';


-- =====================================================================================
--  4. OBJETS PARENTS DU PÉRIMÈTRE ET LEUR CIBLE
-- =====================================================================================
CREATE TABLE INF915_OBJET_PARENT (
  ID_OBJET_PARENT       NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_PARENT_BI
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,
  TYPE_OBJET            VARCHAR2(8)     NOT NULL,   -- CONTRAT | SI | CF | LOT

  -- Objet source, résolu et figé à la validation
  ID_OBJET_SOURCE       NUMBER(12)      NOT NULL,   -- OBJID Clarify

  -- Lignes du périmètre rattachées à cet objet. Sert à l'affichage et au découpage
  -- des lots de traitement, pas à la déduction de l'opération : celle-ci ne dépend
  -- que du type d'objet modifié, du nombre de cibles et de la maille.
  NB_LIGNES             NUMBER(8)       DEFAULT 0 NOT NULL,

  -- Ce que devient l'objet
  TYPE_CIBLE            VARCHAR2(10)    NOT NULL,   -- IDENTIQUE | EXISTANT | CREATION

  -- Objet cible : connu dès la validation pour IDENTIQUE et EXISTANT,
  -- alimenté par le worker séquentiel pour CREATION.
  ID_OBJET_CIBLE        NUMBER(12),

  -- Phase séquentielle
  STATUT                VARCHAR2(12)    DEFAULT 'A_TRAITER' NOT NULL,
  DATE_TRAITEMENT       TIMESTAMP,
  NB_TENTATIVES         NUMBER(3)       DEFAULT 0 NOT NULL,
  CODE_ERREUR           VARCHAR2(40),
  MSG_ERREUR            VARCHAR2(500),

  CONSTRAINT PK_INF915_PARENT       PRIMARY KEY (ID_OBJET_PARENT),
  CONSTRAINT FK_INF915_PARENT_NOT   FOREIGN KEY (ID_NOTIFICATION)
      REFERENCES INF915_NOTIFICATIONS (ID_NOTIFICATION) ON DELETE CASCADE,
  CONSTRAINT UK_INF915_PARENT       UNIQUE (ID_NOTIFICATION, TYPE_OBJET, ID_OBJET_SOURCE),
  CONSTRAINT CK_INF915_PARENT_TYPE  CHECK (TYPE_OBJET IN ('CONTRAT','SI','CF','LOT')),
  CONSTRAINT CK_INF915_PARENT_CIBLE CHECK (TYPE_CIBLE IN ('IDENTIQUE','EXISTANT','CREATION')),
  CONSTRAINT CK_INF915_PARENT_STAT  CHECK (STATUT IN ('A_TRAITER','SANS_OBJET','CREE','REUTILISE','ERREUR')),
  CONSTRAINT CK_INF915_PARENT_LOT   CHECK (TYPE_OBJET <> 'LOT' OR TYPE_CIBLE = 'CREATION'),
  CONSTRAINT CK_INF915_PARENT_RESOL CHECK (TYPE_CIBLE = 'CREATION' OR ID_OBJET_CIBLE IS NOT NULL),
  CONSTRAINT CK_INF915_PARENT_IDENT CHECK (TYPE_CIBLE <> 'IDENTIQUE' OR ID_OBJET_CIBLE = ID_OBJET_SOURCE)
);

CREATE INDEX IX_INF915_PARENT_TRT ON INF915_OBJET_PARENT (ID_NOTIFICATION, STATUT);
CREATE INDEX IX_INF915_PARENT_SRC ON INF915_OBJET_PARENT (ID_NOTIFICATION, TYPE_OBJET, ID_OBJET_SOURCE);

COMMENT ON TABLE INF915_OBJET_PARENT IS
  'Une ligne par objet parent distinct du perimetre : contrats, sites d installation, sites de facturation et lots portes par les lignes retenues';
COMMENT ON COLUMN INF915_OBJET_PARENT.TYPE_CIBLE IS
  'IDENTIQUE = la cible est l objet source. EXISTANT = objet designe ; plusieurs sources vers la meme cible expriment une centralisation. CREATION = objet a creer.';

-- Nommage des objets créés : repris de l'objet source. Si un nommage libre devient
-- une exigence, ajouter NOM_CIBLE VARCHAR2(160) ici.


-- =====================================================================================
--  5. LIGNES DE LA DEMANDE  (le périmètre figé)
-- =====================================================================================
CREATE TABLE INF915_LIGNE (
  ID_LIGNE              NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_LIGNE_BI
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,

  -- Identification de la BdS. Numéro de ligne, IDS et offre restent dans le référentiel.
  ID_CONTR_ITM          NUMBER(12)      NOT NULL,   -- OBJID TABLE_CONTR_ITM (BdS1)
  ID_LIGNE_PORTEUSE     NUMBER(12),                 -- accès porteur, résolu à la validation

  -- Rattachement source, figé. Ces quatre colonnes désignent les objets parents
  -- et permettent de retrouver la cible sans relire le parc.
  ID_CONTRAT_SOURCE     NUMBER(12)      NOT NULL,
  ID_SI_SOURCE          NUMBER(12)      NOT NULL,
  ID_CF_SOURCE          NUMBER(12)      NOT NULL,
  ID_LOT_SOURCE         NUMBER(12)      NOT NULL,

  -- Statuts du parc au moment de la validation. Contrairement aux libellés, ceux-ci
  -- sont historisés : ce sont les valeurs qui ont servi aux contrôles, et elles
  -- changent entre la validation et l'exécution.
  STATUT_ACT_SOURCE     VARCHAR2(40),
  STATUT_MAT_SOURCE     VARCHAR2(40),

  -- Rattachement cible, recopié depuis INF915_OBJET_PARENT une fois les objets créés
  ID_CONTRAT_CIBLE      NUMBER(12),
  ID_SI_CIBLE           NUMBER(12),
  ID_CF_CIBLE           NUMBER(12),
  ID_LOT_CIBLE          NUMBER(12),
  ID_CONTR_ITM_CIBLE    NUMBER(12),                 -- BdS créée sur la cible

  -- Exécution
  -- Pas de statut de contrôle : une ligne n'entre ici que si elle est éligible,
  -- les contrôles ayant été joués en amont par le service d'acquisition.
  STATUT                VARCHAR2(20)    DEFAULT 'A_TRAITER' NOT NULL,
  ETAPE                 VARCHAR2(40),
  NB_TENTATIVES         NUMBER(3)       DEFAULT 0 NOT NULL,
  ID_WORKER             VARCHAR2(60),               -- worker ayant pris la ligne en charge
  ID_ACTION_RELANCE     NUMBER(12),                 -- dernière relance ayant visé la ligne
  DATE_DEBUT            TIMESTAMP,
  DATE_FIN              TIMESTAMP,
  CODE_ERREUR           VARCHAR2(40),
  MSG_ERREUR            VARCHAR2(500),

  CONSTRAINT PK_INF915_LIGNE      PRIMARY KEY (ID_LIGNE),
  CONSTRAINT FK_INF915_LIGNE_NOT  FOREIGN KEY (ID_NOTIFICATION)
      REFERENCES INF915_NOTIFICATIONS (ID_NOTIFICATION) ON DELETE CASCADE,
  CONSTRAINT FK_INF915_LIGNE_PORT FOREIGN KEY (ID_LIGNE_PORTEUSE)
      REFERENCES INF915_LIGNE (ID_LIGNE),
  CONSTRAINT FK_INF915_LIGNE_ACT  FOREIGN KEY (ID_ACTION_RELANCE)
      REFERENCES INF915_ACTION (ID_ACTION),
  CONSTRAINT UK_INF915_LIGNE      UNIQUE (ID_NOTIFICATION, ID_CONTR_ITM),
  CONSTRAINT CK_INF915_LIGNE_STAT CHECK (STATUT IN (
      'A_TRAITER',
      'EN_COURS',
      'TRANSFEREE',
      'ERREUR_METIER',      -- le parc a changé depuis la création, la ligne n'est
                            -- plus transférable au moment de l'exécution
      'ERREUR_TECHNIQUE'))
);

CREATE INDEX IX_INF915_LIGNE_TRT  ON INF915_LIGNE (ID_NOTIFICATION, STATUT);
CREATE INDEX IX_INF915_LIGNE_ITM  ON INF915_LIGNE (ID_CONTR_ITM);
CREATE INDEX IX_INF915_LIGNE_PORT ON INF915_LIGNE (ID_LIGNE_PORTEUSE);
CREATE INDEX IX_INF915_LIGNE_LOT  ON INF915_LIGNE (ID_NOTIFICATION, ID_LOT_SOURCE);
CREATE INDEX IX_INF915_LIGNE_RELA ON INF915_LIGNE (ID_ACTION_RELANCE);
CREATE INDEX IX_INF915_LIGNE_WORK ON INF915_LIGNE (ID_WORKER, STATUT);

COMMENT ON TABLE INF915_LIGNE IS
  'Le perimetre materialise. Une ligne par IDS retenu, avec son rattachement source fige et son rattachement cible resolu.';
COMMENT ON COLUMN INF915_LIGNE.ID_LIGNE_PORTEUSE IS
  'Renseigne pour les lignes rattachees a un acces. La porteuse est dans la meme demande, ce qui supprime le besoin de demandes filles.';
COMMENT ON COLUMN INF915_LIGNE.ID_WORKER IS
  'Instance ayant pris la ligne en charge. Sert au partage du travail entre workers paralleles : chacun marque les lignes qu il prend, puis ne traite que les siennes.';
COMMENT ON COLUMN INF915_LIGNE.ID_ACTION_RELANCE IS
  'Derniere relance ayant vise cette ligne. Croise avec INF915_ACTION, donne qui a relance et quand.';
COMMENT ON COLUMN INF915_LIGNE.ID_CONTR_ITM_CIBLE IS
  'OBJID de la BdS creee sur le parc cible. Sert a l idempotence : une ligne deja valorisee ne doit pas etre rejouee.';


-- =====================================================================================
--  6. RÉSULTATS DE CONTRÔLE
-- =====================================================================================
CREATE TABLE INF915_CONTROLE (
  ID_CONTROLE           NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_CTRL_BI
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,
  ID_LIGNE              NUMBER(12),                 -- NULL = contrôle de portée globale
  ID_ACTION             NUMBER(12),                 -- passe de contrôle qui l'a produit
  CODE_CONTROLE         VARCHAR2(40)    NOT NULL,
  NIVEAU                VARCHAR2(14)    NOT NULL,   -- BLOQUANT | AVERTISSEMENT | INFO
  RESULTAT              VARCHAR2(10)    NOT NULL,   -- OK | KO | SANS_OBJET
  PHASE                 VARCHAR2(12)    NOT NULL,   -- ACQUISITION | EXECUTION
  MSG                   VARCHAR2(500),
  DATE_CONTROLE         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT PK_INF915_CTRL       PRIMARY KEY (ID_CONTROLE),
  CONSTRAINT FK_INF915_CTRL_NOT   FOREIGN KEY (ID_NOTIFICATION)
      REFERENCES INF915_NOTIFICATIONS (ID_NOTIFICATION) ON DELETE CASCADE,
  CONSTRAINT FK_INF915_CTRL_LIG   FOREIGN KEY (ID_LIGNE)
      REFERENCES INF915_LIGNE (ID_LIGNE) ON DELETE CASCADE,
  CONSTRAINT FK_INF915_CTRL_ACT   FOREIGN KEY (ID_ACTION)
      REFERENCES INF915_ACTION (ID_ACTION),
  CONSTRAINT CK_INF915_CTRL_NIV   CHECK (NIVEAU   IN ('BLOQUANT','AVERTISSEMENT','INFO')),
  CONSTRAINT CK_INF915_CTRL_RES   CHECK (RESULTAT IN ('OK','KO','SANS_OBJET')),
  CONSTRAINT CK_INF915_CTRL_PHASE CHECK (PHASE    IN ('ACQUISITION','EXECUTION'))
);

CREATE INDEX IX_INF915_CTRL_NOT ON INF915_CONTROLE (ID_NOTIFICATION, RESULTAT, NIVEAU);
CREATE INDEX IX_INF915_CTRL_LIG ON INF915_CONTROLE (ID_LIGNE);
CREATE INDEX IX_INF915_CTRL_ACT ON INF915_CONTROLE (ID_ACTION);

COMMENT ON TABLE INF915_CONTROLE IS
  'Trace des controles. ACQUISITION : resultats du service web synchrone, recopies a la creation pour justifier le perimetre retenu. EXECUTION : controles rejoues par le worker, qui peuvent echouer si le parc a change depuis.';


-- =====================================================================================
--  7. JOURNAL D'EXÉCUTION, LIGNE PAR LIGNE
--     Gros volume, purgeable. L'historique métier reste dans INF915_ACTION.
-- =====================================================================================
CREATE TABLE INF915_EVENEMENT (
  ID_EVENEMENT          NUMBER(12)      NOT NULL,   -- alimenté par TRG_INF915_EVT_BI
  ID_NOTIFICATION       NUMBER(12)      NOT NULL,
  ID_LIGNE              NUMBER(12),
  ID_OBJET_PARENT       NUMBER(12),
  ID_ACTION             NUMBER(12),                 -- action qui a déclenché l'événement
  ETAPE                 VARCHAR2(40)    NOT NULL,
  STATUT_AVANT          VARCHAR2(20),
  STATUT_APRES          VARCHAR2(20),
  CODE_ERREUR           VARCHAR2(40),
  MSG                   VARCHAR2(1000),
  ID_WORKER             VARCHAR2(60),
  DATE_EVT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT PK_INF915_EVT     PRIMARY KEY (ID_EVENEMENT),
  CONSTRAINT FK_INF915_EVT_NOT FOREIGN KEY (ID_NOTIFICATION)
      REFERENCES INF915_NOTIFICATIONS (ID_NOTIFICATION) ON DELETE CASCADE,
  CONSTRAINT FK_INF915_EVT_ACT FOREIGN KEY (ID_ACTION)
      REFERENCES INF915_ACTION (ID_ACTION)
);

CREATE INDEX IX_INF915_EVT_NOT ON INF915_EVENEMENT (ID_NOTIFICATION, DATE_EVT DESC);
CREATE INDEX IX_INF915_EVT_LIG ON INF915_EVENEMENT (ID_LIGNE, DATE_EVT DESC);
CREATE INDEX IX_INF915_EVT_ACT ON INF915_EVENEMENT (ID_ACTION);

COMMENT ON TABLE INF915_EVENEMENT IS
  'Journal technique ligne par ligne. Volume eleve, purgeable apres quelques mois : l historique metier de la demande est dans INF915_ACTION.';
COMMENT ON COLUMN INF915_EVENEMENT.ID_ACTION IS
  'Action a l origine de l evenement. Permet de savoir exactement quelles lignes une relance donnee a touchees.';


-- =====================================================================================
--  7bis. TABLES TEMPORAIRES D'ACQUISITION
--
--  Interface d'entrée du service web de captation. Plutôt que de faire traverser des
--  dizaines de milliers d'identifiants par des collections PL/SQL, le service les
--  insère en masse dans ces deux tables temporaires, par lots JDBC, puis appelle
--  INF915_PY.PR_CREER_DEMANDE qui travaille en SQL ensembliste.
--
--  Sur cent mille lignes, la différence est décisive : une insertion par lots suivie de
--  quelques INSERT ... SELECT, contre cent mille allers-retours ou une collection de
--  cent mille éléments à sérialiser puis à parcourir.
--
--  ON COMMIT PRESERVE ROWS : le service peut valider entre deux lots sans perdre ce
--  qu'il a déjà inséré. Les lignes vivent le temps de la session et PR_CREER_DEMANDE
--  les purge en fin de traitement, réussite ou échec.
-- =====================================================================================

-- Le périmètre, désigné par identifiant fonctionnel et non par objid : le service web
-- raisonne en master id, c'est-à-dire en TABLE_CONTR_ITM.X_AV_ID_EDS. La résolution en
-- objid est faite par PR_CREER_DEMANDE.
--
-- Le rattachement accompagne chaque ligne plutôt que d'être passé en filtre global. La
-- raison est double. D'abord le parcours autorise plusieurs contrats, plusieurs sites
-- d'installation et plusieurs sites de facturation dans un même périmètre : un filtre
-- scalaire ne saurait pas l'exprimer. Ensuite et surtout, un master id peut exister sur
-- plusieurs BdS, et seul le rattachement exact de la ligne retenue lève l'ambiguïté.
-- La jointure devient ainsi une égalité stricte sur quatre colonnes, ce qui la rend à
-- la fois exacte et efficace sur de gros volumes.
--
-- Le service dispose de ces trois valeurs sans effort : ce sont celles qu'il a
-- affichées au conseiller en constituant la sélection.
CREATE GLOBAL TEMPORARY TABLE INF915_TMP_LIGNE (
  MASTER_ID             VARCHAR2(60)    NOT NULL,
  ID_CONTRAT_SOURCE     NUMBER(12)      NOT NULL,
  ID_SI_SOURCE          NUMBER(12)      NOT NULL,
  ID_CF_SOURCE          NUMBER(12)      NOT NULL
) ON COMMIT PRESERVE ROWS;

COMMENT ON TABLE INF915_TMP_LIGNE IS
  'Perimetre d une demande en cours de captation : un master id et son rattachement contrat, SI, CF. Alimentee par lots par le service web, lue puis purgee par INF915_PY.PR_CREER_DEMANDE.';
COMMENT ON COLUMN INF915_TMP_LIGNE.MASTER_ID IS
  'Identifiant fonctionnel de la ligne de service, rapproche de TABLE_CONTR_ITM.X_AV_ID_EDS.';

-- Le mapping : une ligne par objet parent qui ne reste pas identique à lui-même. Les
-- objets absents de cette table sont conservés tels quels.
CREATE GLOBAL TEMPORARY TABLE INF915_TMP_CIBLE (
  TYPE_OBJET            VARCHAR2(8)     NOT NULL,   -- CONTRAT | SI | CF
  ID_OBJET_SOURCE       NUMBER(12)      NOT NULL,
  TYPE_CIBLE            VARCHAR2(10)    NOT NULL,   -- EXISTANT | CREATION
  ID_OBJET_CIBLE        NUMBER(12)                  -- NULL si CREATION
) ON COMMIT PRESERVE ROWS;

CREATE INDEX IX_INF915_TMP_CIBLE ON INF915_TMP_CIBLE (TYPE_OBJET, ID_OBJET_SOURCE);

COMMENT ON TABLE INF915_TMP_CIBLE IS
  'Mapping source vers cible d une demande en cours de captation. Les lots ne figurent jamais ici : leur structure est toujours reproduite a l identique.';


-- =====================================================================================
--  8. SÉQUENCES ET TRIGGERS D'IDENTIFIANT
--     Remplace les colonnes IDENTITY, indisponibles avant la 12c.
--     Le test IS NULL reproduit la sémantique GENERATED BY DEFAULT.
-- =====================================================================================
CREATE SEQUENCE SEQ_INF915_NOTIF  START WITH 1 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE SEQ_INF915_ACTION START WITH 1 INCREMENT BY 1 CACHE 20  NOCYCLE;
CREATE SEQUENCE SEQ_INF915_PARENT START WITH 1 INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE SEQ_INF915_LIGNE  START WITH 1 INCREMENT BY 1 CACHE 200 NOCYCLE;
CREATE SEQUENCE SEQ_INF915_CTRL   START WITH 1 INCREMENT BY 1 CACHE 200 NOCYCLE;
CREATE SEQUENCE SEQ_INF915_EVT    START WITH 1 INCREMENT BY 1 CACHE 200 NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_INF915_NOTIF_BI
BEFORE INSERT ON INF915_NOTIFICATIONS
FOR EACH ROW
BEGIN
  IF :NEW.ID_NOTIFICATION IS NULL THEN
    :NEW.ID_NOTIFICATION := SEQ_INF915_NOTIF.NEXTVAL;
  END IF;
END;
/

-- Garde-fou sur les transitions de statut. Empêche un worker ou un correctif de
-- faire sauter le point d'arrêt, ou de rouvrir une demande close.
CREATE OR REPLACE TRIGGER TRG_INF915_NOTIF_BU
BEFORE UPDATE OF STATUT ON INF915_NOTIFICATIONS
FOR EACH ROW
WHEN (OLD.STATUT <> NEW.STATUT)
DECLARE
  c_ok CONSTANT VARCHAR2(1000) :=
    '|EN_ATTENTE>EN_COURS_PARENTS' || '|EN_ATTENTE>EN_COURS_LIGNES'       ||
    '|EN_ATTENTE>ANNULEE'          ||
    '|EN_COURS_PARENTS>PARENTS_CREES'    || '|EN_COURS_PARENTS>PARENTS_EN_ERREUR' ||
    '|PARENTS_EN_ERREUR>EN_COURS_PARENTS'|| '|PARENTS_EN_ERREUR>PARENTS_CREES'    ||
    '|PARENTS_EN_ERREUR>ANNULEE'   ||
    '|PARENTS_CREES>EN_ATTENTE_TRT_LIGNES'   || '|PARENTS_CREES>ANNULEE'          ||
    '|EN_ATTENTE_TRT_LIGNES>EN_COURS_LIGNES' || '|EN_ATTENTE_TRT_LIGNES>ANNULEE'  ||
    '|EN_COURS_LIGNES>TRAITEE'     || '|EN_COURS_LIGNES>TRAITEE_PARTIELLE' ||
    '|EN_COURS_LIGNES>EN_ERREUR'   ||
    '|EN_ERREUR>EN_COURS_LIGNES'   || '|EN_ERREUR>TRAITEE_PARTIELLE'       ||
    '|TRAITEE_PARTIELLE>EN_COURS_LIGNES' || '|TRAITEE_PARTIELLE>TRAITEE'   || '|';
BEGIN
  IF INSTR (c_ok, '|' || :OLD.STATUT || '>' || :NEW.STATUT || '|') = 0 THEN
    RAISE_APPLICATION_ERROR (-20917,
      'INF915 : transition de statut interdite, ' || :OLD.STATUT || ' -> ' || :NEW.STATUT);
  END IF;

  -- Le point d'arrêt ne se saute que si rien n'a été créé.
  IF :OLD.STATUT = 'EN_ATTENTE' AND :NEW.STATUT = 'EN_COURS_LIGNES'
     AND NVL (:NEW.NB_OBJETS_A_CREER, 0) > 0 THEN
    RAISE_APPLICATION_ERROR (-20918,
      'INF915 : ' || :NEW.NB_OBJETS_A_CREER || ' objet(s) a creer, la demande doit ' ||
      'passer par EN_COURS_PARENTS puis PARENTS_CREES.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INF915_ACTION_BI
BEFORE INSERT ON INF915_ACTION
FOR EACH ROW
BEGIN
  IF :NEW.ID_ACTION IS NULL THEN
    :NEW.ID_ACTION := SEQ_INF915_ACTION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INF915_PARENT_BI
BEFORE INSERT ON INF915_OBJET_PARENT
FOR EACH ROW
BEGIN
  IF :NEW.ID_OBJET_PARENT IS NULL THEN
    :NEW.ID_OBJET_PARENT := SEQ_INF915_PARENT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INF915_LIGNE_BI
BEFORE INSERT ON INF915_LIGNE
FOR EACH ROW
BEGIN
  IF :NEW.ID_LIGNE IS NULL THEN
    :NEW.ID_LIGNE := SEQ_INF915_LIGNE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INF915_CTRL_BI
BEFORE INSERT ON INF915_CONTROLE
FOR EACH ROW
BEGIN
  IF :NEW.ID_CONTROLE IS NULL THEN
    :NEW.ID_CONTROLE := SEQ_INF915_CTRL.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INF915_EVT_BI
BEFORE INSERT ON INF915_EVENEMENT
FOR EACH ROW
BEGIN
  IF :NEW.ID_EVENEMENT IS NULL THEN
    :NEW.ID_EVENEMENT := SEQ_INF915_EVT.NEXTVAL;
  END IF;
END;
/

-- Cache différencié. NOCACHE sur les demandes, peu nombreuses, pour éviter les trous
-- d'identifiant visibles du métier. Cache faible sur les actions, quelques lignes par
-- demande. Cache large sur les lignes, contrôles et événements, insérés en masse par
-- les workers parallèles, où les trous sont sans conséquence.


-- =====================================================================================
--  9. VUE DES JALONS
--     Pivote INF915_ACTION pour retrouver, en une ligne par demande, les dates et
--     acteurs clés. Remplace exactement les colonnes d'audit supprimées de l'en-tête,
--     en ajoutant ce qu'elles ne savaient pas porter : l'annulation et les relances.
-- =====================================================================================
CREATE OR REPLACE VIEW INF915_V_JALON AS
SELECT ID_NOTIFICATION,
       MIN(CASE WHEN TYPE_ACTION = 'CREATION'         THEN DATE_ACTION END) AS DATE_CREATION,
       MAX(CASE WHEN TYPE_ACTION = 'CREATION'         THEN ACTEUR      END) AS CREE_PAR,
       MAX(CASE WHEN TYPE_ACTION = 'ANNULATION'       THEN DATE_ACTION END) AS DATE_ANNULATION,
       MAX(CASE WHEN TYPE_ACTION = 'ANNULATION'       THEN ACTEUR      END) AS ANNULE_PAR,
       MAX(CASE WHEN TYPE_ACTION = 'ANNULATION'       THEN MOTIF       END) AS MOTIF_ANNULATION,
       MIN(CASE WHEN TYPE_ACTION = 'DEBUT_PARENTS'      THEN DATE_ACTION END) AS DATE_DEBUT_PARENTS,
       MAX(CASE WHEN TYPE_ACTION = 'FIN_PARENTS'        THEN DATE_ACTION END) AS DATE_FIN_PARENTS,
       MAX(CASE WHEN TYPE_ACTION = 'VALIDATION_PARENTS' THEN DATE_ACTION END) AS DATE_VALID_PARENTS,
       MAX(CASE WHEN TYPE_ACTION = 'VALIDATION_PARENTS' THEN ACTEUR      END) AS VALID_PARENTS_PAR,
       MIN(CASE WHEN TYPE_ACTION = 'DEBUT_LIGNES'       THEN DATE_ACTION END) AS DATE_DEBUT_LIGNES,
       MAX(CASE WHEN TYPE_ACTION = 'FIN_TRAITEMENT'     THEN DATE_ACTION END) AS DATE_FIN_TRT,
       SUM(CASE WHEN TYPE_ACTION = 'RELANCE'          THEN 1 ELSE 0    END) AS NB_RELANCES,
       MAX(CASE WHEN TYPE_ACTION = 'RELANCE'          THEN DATE_ACTION END) AS DATE_DER_RELANCE,
       MAX(CASE WHEN TYPE_ACTION = 'RELANCE'          THEN ACTEUR      END) AS DER_RELANCE_PAR
FROM   INF915_ACTION
GROUP  BY ID_NOTIFICATION;


-- =====================================================================================
--  10. VUE DE SUIVI  (écran RC360)
--      Les libellés d'organisation sont résolus par l'IHM à partir des identifiants.
-- =====================================================================================
CREATE OR REPLACE VIEW INF915_V_SUIVI AS
SELECT n.ID_NOTIFICATION,
       n.REFERENCE,
       NVL (o.LIBELLE, 'En attente de qualification')        AS LIB_OPERATION,
       n.MAILLE,
       n.ID_ORGA_SOURCE,
       NVL(n.ID_ORGA_CIBLE, n.ID_ORGA_SOURCE)                AS ID_ORGA_CIBLE,
       n.DATE_EFFET,
       n.STATUT,
       n.NB_LIGNES,
       n.NB_CONTRATS,
       n.NB_SI,
       n.NB_CF,
       n.NB_LOTS,
       n.NB_LIGNES_OK,
       n.NB_LIGNES_KO_METIER + n.NB_LIGNES_KO_TECH           AS NB_LIGNES_KO,
       CASE WHEN n.NB_LIGNES = 0 THEN 0
            ELSE ROUND(100 * n.NB_LIGNES_OK / n.NB_LIGNES, 1)
       END                                                    AS PCT_AVANCEMENT,
       n.NB_OBJETS_A_CREER,
       n.NB_OBJETS_CREES,
       j.DATE_CREATION,
       j.CREE_PAR,
       j.DATE_ANNULATION,
       j.ANNULE_PAR,
       j.MOTIF_ANNULATION,
       j.DATE_DEBUT_PARENTS,
       j.DATE_FIN_PARENTS,
       j.DATE_VALID_PARENTS,
       j.VALID_PARENTS_PAR,
       j.DATE_DEBUT_LIGNES,
       j.DATE_FIN_TRT,
       j.NB_RELANCES,
       j.DATE_DER_RELANCE,
       j.DER_RELANCE_PAR
FROM        INF915_NOTIFICATIONS n
LEFT   JOIN INF915_REF_OPERATION o ON o.CODE_OPERATION  = n.CODE_OPERATION
LEFT   JOIN INF915_V_JALON       j ON j.ID_NOTIFICATION = n.ID_NOTIFICATION;


-- =====================================================================================
--  11. VUE DE VOLUMÉTRIE RECALCULÉE
--      Équivalent des compteurs de l'en-tête, si vous préférez les supprimer.
-- =====================================================================================
CREATE OR REPLACE VIEW INF915_V_VOLUMETRIE AS
SELECT n.ID_NOTIFICATION,
       (SELECT COUNT(*) FROM INF915_LIGNE l
         WHERE l.ID_NOTIFICATION = n.ID_NOTIFICATION)                            AS NB_LIGNES,
       (SELECT COUNT(*) FROM INF915_LIGNE l
         WHERE l.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND l.STATUT = 'TRANSFEREE')                                          AS NB_LIGNES_OK,
       (SELECT COUNT(*) FROM INF915_LIGNE l
         WHERE l.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND l.STATUT IN ('ERREUR_METIER','ERREUR_TECHNIQUE'))                 AS NB_LIGNES_KO,
       (SELECT COUNT(*) FROM INF915_OBJET_PARENT p
         WHERE p.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND p.TYPE_OBJET = 'CONTRAT')                                         AS NB_CONTRATS,
       (SELECT COUNT(*) FROM INF915_OBJET_PARENT p
         WHERE p.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND p.TYPE_OBJET = 'SI')                                              AS NB_SI,
       (SELECT COUNT(*) FROM INF915_OBJET_PARENT p
         WHERE p.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND p.TYPE_OBJET = 'CF')                                              AS NB_CF,
       (SELECT COUNT(*) FROM INF915_OBJET_PARENT p
         WHERE p.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND p.TYPE_OBJET = 'LOT')                                             AS NB_LOTS,
       (SELECT COUNT(*) FROM INF915_OBJET_PARENT p
         WHERE p.ID_NOTIFICATION = n.ID_NOTIFICATION
           AND p.TYPE_CIBLE = 'CREATION')                                        AS NB_OBJETS_A_CREER
FROM   INF915_NOTIFICATIONS n;


-- =====================================================================================
--  12. REQUÊTES DE RÉFÉRENCE
-- =====================================================================================
--
--  HISTORIQUE D'UNE DEMANDE, tel que l'affiche l'écran de suivi.
--
--    SELECT DATE_ACTION, TYPE_ACTION, ACTEUR, TYPE_ACTEUR,
--           STATUT_AVANT, STATUT_APRES, PORTEE, NB_LIGNES_VISEES, MOTIF
--    FROM   INF915_ACTION
--    WHERE  ID_NOTIFICATION = :id
--    ORDER  BY DATE_ACTION, ID_ACTION;
--
--
--  ANNULATION D'UNE DEMANDE, avec son auteur et son motif.
--
--    INSERT INTO INF915_ACTION
--      (ID_NOTIFICATION, TYPE_ACTION, ACTEUR, TYPE_ACTEUR,
--       STATUT_AVANT, STATUT_APRES, MOTIF)
--    VALUES (:id, 'ANNULATION', :login, 'UTILISATEUR',
--            :statut_courant, 'ANNULEE', :motif);
--
--    UPDATE INF915_NOTIFICATIONS SET STATUT = 'ANNULEE'
--     WHERE ID_NOTIFICATION = :id AND STATUT NOT IN ('TRAITEE','ANNULEE');
--
--
--  FRANCHISSEMENT DU POINT D'ARRÊT : le métier a vérifié les objets créés et lance
--  la phase lignes. Rien d'automatique ici, c'est une action humaine tracée.
--
--    INSERT INTO INF915_ACTION
--      (ID_NOTIFICATION, TYPE_ACTION, ACTEUR, TYPE_ACTEUR, STATUT_AVANT, STATUT_APRES)
--    VALUES (:id, 'VALIDATION_PARENTS', :login, 'UTILISATEUR',
--            'PARENTS_CREES', 'EN_ATTENTE_TRT_LIGNES');
--
--    UPDATE INF915_NOTIFICATIONS SET STATUT = 'EN_ATTENTE_TRT_LIGNES'
--     WHERE ID_NOTIFICATION = :id AND STATUT = 'PARENTS_CREES';
--
--  La demande attend ensuite qu'un worker la prenne, ce qu'il trace par une action
--  DEBUT_LIGNES et un passage en EN_COURS_LIGNES. À partir de là, plus d'annulation.
--
--    SELECT ID_NOTIFICATION FROM INF915_NOTIFICATIONS
--     WHERE STATUT = 'EN_ATTENTE_TRT_LIGNES' AND DATE_EFFET <= TRUNC (SYSDATE)
--     ORDER BY ID_NOTIFICATION;
--
--
--  DEMANDES EN ATTENTE DU FEU VERT MÉTIER, pour l'écran de suivi.
--
--    SELECT n.ID_NOTIFICATION, n.REFERENCE, n.NB_OBJETS_CREES, j.DATE_FIN_PARENTS
--    FROM   INF915_NOTIFICATIONS n
--    JOIN   INF915_V_JALON       j ON j.ID_NOTIFICATION = n.ID_NOTIFICATION
--    WHERE  n.STATUT = 'PARENTS_CREES'
--    ORDER  BY j.DATE_FIN_PARENTS;
--
--
--  OBJETS CRÉÉS À VÉRIFIER PAR LE MÉTIER, sur une demande au point d'arrêt.
--
--    SELECT p.TYPE_OBJET, p.ID_OBJET_SOURCE, p.ID_OBJET_CIBLE, p.NB_LIGNES, p.STATUT
--    FROM   INF915_OBJET_PARENT p
--    WHERE  p.ID_NOTIFICATION = :id
--      AND  p.TYPE_CIBLE      = 'CREATION'
--    ORDER  BY DECODE (p.TYPE_OBJET,'CONTRAT',1,'SI',2,'CF',3,'LOT',4);
--
--
--  RELANCE DES LIGNES EN ERREUR TECHNIQUE, tracée et rattachée aux lignes visées.
--
--    INSERT INTO INF915_ACTION
--      (ID_NOTIFICATION, TYPE_ACTION, ACTEUR, TYPE_ACTEUR, PORTEE, NB_LIGNES_VISEES)
--    VALUES (:id, 'RELANCE', :login, 'UTILISATEUR', 'ERREUR_TECH', :nb)
--    RETURNING ID_ACTION INTO l_id_action;
--
--    UPDATE INF915_LIGNE
--       SET STATUT            = 'A_TRAITER',
--           ID_ACTION_RELANCE = l_id_action,
--           NB_TENTATIVES     = NB_TENTATIVES + 1,
--           CODE_ERREUR       = NULL,
--           MSG_ERREUR        = NULL
--     WHERE ID_NOTIFICATION = :id
--       AND STATUT          = 'ERREUR_TECHNIQUE';
--
--
--  CE QU'UNE RELANCE DONNÉE A EFFECTIVEMENT TOUCHÉ.
--
--    SELECT l.ID_LIGNE, l.ID_CONTR_ITM, l.STATUT
--    FROM   INF915_LIGNE l
--    WHERE  l.ID_ACTION_RELANCE = :id_action;
--
--
--  QUI A FAIT QUOI SUR LA PÉRIODE, pour l'audit.
--
--    SELECT a.ACTEUR, a.TYPE_ACTION, COUNT(*) AS NB
--    FROM   INF915_ACTION a
--    WHERE  a.TYPE_ACTEUR = 'UTILISATEUR'
--      AND  a.DATE_ACTION >= :debut AND a.DATE_ACTION < :fin
--    GROUP  BY a.ACTEUR, a.TYPE_ACTION
--    ORDER  BY a.ACTEUR, a.TYPE_ACTION;
--
--
--  PHASE SÉQUENTIELLE : objets parents à créer, dans l'ordre des dépendances.
--
--    SELECT *
--    FROM   INF915_OBJET_PARENT
--    WHERE  ID_NOTIFICATION = :id
--      AND  STATUT          = 'A_TRAITER'
--      AND  TYPE_CIBLE      = 'CREATION'
--    ORDER  BY DECODE(TYPE_OBJET,'CONTRAT',1,'SI',2,'CF',3,'LOT',4), ID_OBJET_PARENT;
--
--
--  REPORT DES CIBLES SUR LES LIGNES, avant la phase parallèle.
--
--    UPDATE INF915_LIGNE l
--       SET l.ID_CONTRAT_CIBLE = (SELECT p.ID_OBJET_CIBLE FROM INF915_OBJET_PARENT p
--                                  WHERE p.ID_NOTIFICATION = l.ID_NOTIFICATION
--                                    AND p.TYPE_OBJET      = 'CONTRAT'
--                                    AND p.ID_OBJET_SOURCE = l.ID_CONTRAT_SOURCE),
--           l.ID_SI_CIBLE      = (SELECT p.ID_OBJET_CIBLE FROM INF915_OBJET_PARENT p
--                                  WHERE p.ID_NOTIFICATION = l.ID_NOTIFICATION
--                                    AND p.TYPE_OBJET      = 'SI'
--                                    AND p.ID_OBJET_SOURCE = l.ID_SI_SOURCE),
--           l.ID_CF_CIBLE      = (SELECT p.ID_OBJET_CIBLE FROM INF915_OBJET_PARENT p
--                                  WHERE p.ID_NOTIFICATION = l.ID_NOTIFICATION
--                                    AND p.TYPE_OBJET      = 'CF'
--                                    AND p.ID_OBJET_SOURCE = l.ID_CF_SOURCE),
--           l.ID_LOT_CIBLE     = (SELECT p.ID_OBJET_CIBLE FROM INF915_OBJET_PARENT p
--                                  WHERE p.ID_NOTIFICATION = l.ID_NOTIFICATION
--                                    AND p.TYPE_OBJET      = 'LOT'
--                                    AND p.ID_OBJET_SOURCE = l.ID_LOT_SOURCE),
--     WHERE l.ID_NOTIFICATION = :id
--       AND l.STATUT          = 'A_TRAITER';
--
--
--  PRISE DE LOT PAR UN WORKER PARALLÈLE. SKIP LOCKED n'est pas documenté en 11g :
--  marquage atomique plutôt que verrouillage.
--
--    UPDATE INF915_LIGNE
--       SET STATUT = 'EN_COURS', DATE_DEBUT = SYSTIMESTAMP
--     WHERE ID_LIGNE IN (SELECT ID_LIGNE FROM (
--             SELECT ID_LIGNE FROM INF915_LIGNE
--              WHERE ID_NOTIFICATION = :id AND STATUT = 'A_TRAITER'
--              ORDER BY ID_LIGNE) WHERE ROWNUM <= :taille_lot)
--    RETURNING ID_LIGNE BULK COLLECT INTO l_ids;
--
--
--  RELECTURE D'UNE DEMANDE : ce qui change, type d'objet par type d'objet.
--
--    SELECT TYPE_OBJET,
--           COUNT(*)                                                AS NB_SOURCES,
--           SUM(CASE WHEN TYPE_CIBLE='IDENTIQUE' THEN 1 ELSE 0 END)  AS NB_INCHANGES,
--           SUM(CASE WHEN TYPE_CIBLE='EXISTANT'  THEN 1 ELSE 0 END)  AS NB_REUTILISES,
--           SUM(CASE WHEN TYPE_CIBLE='CREATION'  THEN 1 ELSE 0 END)  AS NB_CREATIONS,
--           COUNT(DISTINCT ID_OBJET_CIBLE)                           AS NB_CIBLES
--    FROM   INF915_OBJET_PARENT
--    WHERE  ID_NOTIFICATION = :id
--    GROUP  BY TYPE_OBJET;
--
--    Sur le type CF : 10 sources pour 1 cible, centralisation ; 10 pour 10,
--    décentralisation ; 6 réutilisés et 4 créations, cas mixte.
-- =====================================================================================


-- =====================================================================================
--  EXEMPLE : centralisation de 10 sites de facturation sur un site existant,
--            périmètre d'un contrat, 340 lignes, 12 lots, en masse.
--
--  INF915_NOTIFICATIONS  1 ligne    ID_ORGA_CIBLE = NULL
--                                   CODE_OPERATION = REORG_FACT_CENTRA
--                                   NB_LIGNES=340, NB_CONTRATS=1, NB_SI=4, NB_CF=10, NB_LOTS=12
--  INF915_ACTION         6 lignes   CREATION par dupontj, DEBUT_PARENTS et FIN_PARENTS
--                                   par le worker, VALIDATION_PARENTS par martinl apres
--                                   verification des 12 lots crees, DEBUT_LIGNES et
--                                   FIN_TRAITEMENT par le worker
--  INF915_OBJET_PARENT   1 ligne    TYPE_OBJET=CONTRAT, TYPE_CIBLE=IDENTIQUE
--                        4 lignes   TYPE_OBJET=SI,      TYPE_CIBLE=IDENTIQUE
--                       10 lignes   TYPE_OBJET=CF,      TYPE_CIBLE=EXISTANT, même ID_OBJET_CIBLE
--                       12 lignes   TYPE_OBJET=LOT,     TYPE_CIBLE=CREATION
--  INF915_LIGNE        340 lignes
--
--  Même demande en décentralisation : les 10 lignes CF portent 10 ID_OBJET_CIBLE
--  distincts, ou passent en CREATION, ou un mélange des deux.
--  Changement de titulaire : ID_ORGA_CIBLE renseigné sur l'en-tête, et la ligne
--  TYPE_OBJET=CONTRAT passe en EXISTANT ou CREATION.
-- =====================================================================================
